version: '3.2'
services:
  intesa-vincente:
    container_name: intesa-vincente
    image: intesa-vincente
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - 9001:3301
    environment:
        - PORT=3301
    restart: always